// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIM9jNu77JfYLdFzmDp090I3yolSe1FnM',
    appId: '1:702510615666:web:6b2ae0c8073be09228c6eb',
    messagingSenderId: '702510615666',
    projectId: 'phone-authentication-278c6',
    authDomain: 'phone-authentication-278c6.firebaseapp.com',
    databaseURL: 'https://phone-authentication-278c6-default-rtdb.firebaseio.com',
    storageBucket: 'phone-authentication-278c6.appspot.com',
    measurementId: 'G-6ZPK8K59L4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnkZvmYy7u-9TOfNmOZEQdfXS70MHY8TE',
    appId: '1:702510615666:android:1a1e93f9b63e481328c6eb',
    messagingSenderId: '702510615666',
    projectId: 'phone-authentication-278c6',
    databaseURL: 'https://phone-authentication-278c6-default-rtdb.firebaseio.com',
    storageBucket: 'phone-authentication-278c6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcCI81casXgL42AlQcRqHWo4g-eXposd4',
    appId: '1:702510615666:ios:4b986d20e933de3e28c6eb',
    messagingSenderId: '702510615666',
    projectId: 'phone-authentication-278c6',
    databaseURL: 'https://phone-authentication-278c6-default-rtdb.firebaseio.com',
    storageBucket: 'phone-authentication-278c6.appspot.com',
    iosBundleId: 'com.example.firebasePhoneAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcCI81casXgL42AlQcRqHWo4g-eXposd4',
    appId: '1:702510615666:ios:4b986d20e933de3e28c6eb',
    messagingSenderId: '702510615666',
    projectId: 'phone-authentication-278c6',
    databaseURL: 'https://phone-authentication-278c6-default-rtdb.firebaseio.com',
    storageBucket: 'phone-authentication-278c6.appspot.com',
    iosBundleId: 'com.example.firebasePhoneAuth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIM9jNu77JfYLdFzmDp090I3yolSe1FnM',
    appId: '1:702510615666:web:94f1ddac675866f328c6eb',
    messagingSenderId: '702510615666',
    projectId: 'phone-authentication-278c6',
    authDomain: 'phone-authentication-278c6.firebaseapp.com',
    databaseURL: 'https://phone-authentication-278c6-default-rtdb.firebaseio.com',
    storageBucket: 'phone-authentication-278c6.appspot.com',
    measurementId: 'G-137MX1PLE1',
  );

}